MozillaSecurity/funfuzz

js/jsfunfuzz/gen-grammar.js, js/shared/testing-functions.js
Bug 683218 removes `__noSuchMethod__`.
[1] https://bugzilla.mozilla.org/show_bug.cgi?id=683218
=> Remove __noSuchMethod__ since bug 683218 is landing.

util/downloadBuild.py, util/subprocesses.py
* The downloadBuild.py script was unable to download win64 builds. Now it is.
* The downloadBuild.py script now has an option to download tests; it no longer downloads them by default. THIS CHANGES THE DEFAULT BEHAVIOR, YOU MAY WISH TO CHANGE THAT BACK.
* The subprocesses.py script required setting some environment variables for no apparent reason, so I removed them to allow the script to work if they are not set.
=> Minor bug fixes and new features

js/shared/testing-functions.js, js/shellFlags.py
The maximum number for gczeal was bumped to 15 in [bug 1272604](https://bugzilla.mozilla.org/show_bug.cgi?id=1272604).
@jruderman: is the change to "rnd(16)" correct? It will then generate numbers 0 to 15 IIRC..
=> Bump gczeal maximum number, see bug 1272604.

util/gdb-quick.txt
This commit comments the "enable unwinder" command in the gdb-quick.txt file.
The used python script does not work with the latest versions of gdb.
=> gdb SpiderMonkey unwinder does not work with latest versions of gdb

js/shared/testing-functions.js, js/shellFlags.py
The maximum number for gczeal was bumped to 16 in bug 1287869.
See a previous number bump in #40. It is an almost identical change so I will merge this right away.
=> Bump gczeal maximum number, see bug 1287869.

js/shellFlags.py
As of m-c rev c91249f41e37, there is another set of js flags that disable all JITs, we should also use this set of compareJIT flags when comparing output.
=> Add another compareJIT flag combination, one that disables baseline, ion and wasm JITs. r=truber

autobisect-js/knownBrokenEarliestWorking.py, js/shellFlags.py
Hannes Vershore mentioned over email that this flag combination is now ready for fuzzing, so let's land this as a start and see if anything on the m-c tree immediately breaks.
=> Add support for --ion-aa=[flow-sensitive|flow-insensitive], r=truber

js/shared/random.js
Fixes a bug reported by "hehe" via IRC.  The last index in an array won't be considered when selecting a random item via Random.choose.
=> Fixed bug preventing last list item from being considered in Random.choose

autobisect-js/knownBrokenEarliestWorking.py, util/subprocesses.py
Ubuntu 17.04 includes sed 4.4, and [m-c ebcbf47a83e7](https://hg.mozilla.org/mozilla-central/rev/ebcbf47a83e7) is a changeset that adds support for sed 4.3+, so update the earliest known rev.
=> [autoBisect] Support sed 4.3+ in Ubuntu 17.04

js/buildOptions.py, js/jsfunfuzz/avoid-known-bugs.js, js/jsfunfuzz/detect-engine.js, js/jsfunfuzz/gen-grammar.js, js/loopjsfunfuzz.py, util/reposUpdate.py
mozilla-aurora is going to die, let's remove it. We are no longer fuzzing ESR much, if any, we should only fuzz mozilla-central and mozilla-beta.
We also need to start moving to octo, and having some of these old code removed will simplify things.
=> Remove support for mozilla-aurora and ESR branches

.appveyor.yml, .travis.yml, js/buildOptions.py, js/compileShell.py, util/forkJoin.py, util/hgCmds.py, util/subprocesses.py, util/tooltool/tooltool.py
These are the remaining changes needed for funfuzz to be forward-compatible with Python 3.
=> Activate flake8 for Python 3

.appveyor.yml, .travis.yml, autobisect-js/autoBisect.py, util/downloadBuild.py, util/hgCmds.py, util/subprocesses.py, util/tooltool/tooltool.py
We should turn on pylint for Python 3 to ensure future code has some form of Python 3-compliance.
Note that even after this PR lands, it will still be some ways before Python 3 is fully supported. (e.g. MozillaBuild 3 needs to be installed on Windows, which [will be released by the end of the month](https://bugzilla.mozilla.org/show_bug.cgi?id=1381614)) Also downloadBuild/tooltool.py needs to be removed/upgraded.
=> [pylint-03] Activate pylint for Python 3, though it is still not fully supported yet

.appveyor.yml, .travis.yml, README.md, autobisect-js/autoBisect.py, js/compareJIT.py, js/inspectShell.py, js/jsInteresting.py, js/pinpoint.py, requirements.txt, util/crashesat.py, util/createCollector.py, util/lithOps.py, util/reposUpdate.py
This seems to be the minimal set of changes necessary to make funfuzz work with Lithium 0.2.0 (currently in [PR #49 over there](https://github.com/MozillaSecurity/lithium/pull/49))
Some changes were adapted from one of [truber's commits](https://github.com/MozillaSecurity/domfuzz/commit/7e462aa842c161db87d29f05275b1d2d89ec3e1c) in domfuzz.
=> Update funfuzz to work with lithium 0.2.0

.appveyor.yml
Adapted from [Lithium PR #56](https://github.com/MozillaSecurity/lithium/pull/56), also moves to Visual Studio 2017.
I will land this after getting the codecov report for this PR to see that everything seems to work as expected.
=> Fix code coverage for Python 2.7 64-bit and 3

src/funfuzz/js/jsfunfuzz/detect-engine.js, src/funfuzz/js/jsfunfuzz/gen-grammar.js, src/funfuzz/js/shell_flags.py
We'll need to issue a new version for this, + pick up all the changes in master since then. This should at least unbreak some parts of jsfunfuzz.
There is more breakage ahead that needs to be fixed, see #146 and #147, but I'll need to do an audit next quarter + discuss w/ the js team at the next All Hands as to future plans.
As for tests, this involves jsfunfuzz only (all js changes) - the upcoming tests PR only involves Python and so should be distinct from each other.
=> Fix #148 - Stop testing the version function.

.appveyor.yml
Details in #150. @jschwartzentruber, do you think this makes sense?
=> Fix #150 - Remove testing with 32-bit Python in AppVeyor.

src/funfuzz/autobisectjs/autobisectjs.py, src/funfuzz/autobisectjs/find_intersecting_changesets.py, src/funfuzz/autobisectjs/known_broken_earliest_working.py, src/funfuzz/bot.py, src/funfuzz/js/build_options.py, src/funfuzz/js/compare_jit.py, src/funfuzz/js/compile_shell.py, src/funfuzz/js/inspect_shell.py, src/funfuzz/js/js_interesting.py, src/funfuzz/js/loop.py, src/funfuzz/js/pinpoint.py, src/funfuzz/js/shell_flags.py, src/funfuzz/loop_bot.py, src/funfuzz/util/crashesat.py, src/funfuzz/util/create_collector.py, src/funfuzz/util/detect_malloc_errors.py, src/funfuzz/util/download_build.py, src/funfuzz/util/file_manipulation.py, src/funfuzz/util/find_ignore_lists.py, src/funfuzz/util/fork_join.py, src/funfuzz/util/hg_helpers.py, src/funfuzz/util/link_js.py, src/funfuzz/util/lithium_helpers.py, src/funfuzz/util/repos_update.py, src/funfuzz/util/s3cache.py, src/funfuzz/util/subprocesses.py
Here's a first wave of Python 3 fixes for funfuzz.
Some strings I've reverted from being set to bytes. This is the only way `configure` runs properly on both Python 2 and 3.
I switched to using the `builtins` and `past.builtins` libraries since we now import the Futurize module and it is also mentioned on the [official porting page](https://docs.python.org/3/howto/pyporting.html#the-short-explanation).
=> First wave of Python 3 fixes

src/funfuzz/js/compile_shell.py
It's now really simple to check whether a binary is available, so check for all the variants: `autoconf2.13`, `autoconf-2.13` and `autoconf213`.
=> Fix #9 - compileShell fails on Fedora due to autoconf 2.13 binary name discrepancy

.appveyor.yml, .travis.yml, setup.py
As per [discussed here](https://github.com/MozillaSecurity/funfuzz/pull/194#discussion_r187733155).
=> Split out PyPI pytest/linter-related dependencies.

src/funfuzz/util/crashesat.py
This still relies on `grabCrashLog` so still remaining at this same location for now.
=> Refactor the crashesat interestingness test to use argparse, logging and pathlib

src/funfuzz/js/loop.py
4abb66c3f583d942e081532a561b444ecad32295 renamed this method and moved it to a new file. However, it never fixed the import, so running loop.py was broken.
=> Rename sps to os_ops in loop.py

src/funfuzz/js/jsfunfuzz/gen-grammar.js, src/funfuzz/js/jsfunfuzz/gen-type-aware-code.js, src/funfuzz/js/jsfunfuzz/run-in-sandbox.js, src/funfuzz/js/shared/testing-functions.js
These are improvements to jsfunfuzz.
Adds:
* `invisibleToDebugger` and `sameCompartmentAs` to `newGlobal` parameters to be tested
* `saveIncrementalBytecode` to `evaluate` parameters
* Initial support for `recomputeWrappers`
* the `keepFailing: true` option to `oomTest`
Removes:
* Support for generator expressions
* `Object.prototype` no longer has `__count__` and `__parent__`.
I am still poking at hooking up eslint to Travis to at least have a linter in place.
=> jsfunfuzz updates: remove generator expressions, support invisibleToDebugger/sameCompartmentAs, recomputeWrappers etc.

.appveyor.yml, .travis.yml, setup.py, src/funfuzz/autobisectjs/autobisectjs.py, src/funfuzz/bot.py, src/funfuzz/js/build_options.py, src/funfuzz/js/compare_jit.py, src/funfuzz/js/compile_shell.py, src/funfuzz/js/inspect_shell.py, src/funfuzz/js/js_interesting.py, src/funfuzz/js/link_fuzzer.py, src/funfuzz/util/crashesat.py, src/funfuzz/util/create_collector.py, src/funfuzz/util/fork_join.py, src/funfuzz/util/hg_helpers.py, src/funfuzz/util/lithium_helpers.py, src/funfuzz/util/lock_dir.py, src/funfuzz/util/os_ops.py, src/funfuzz/util/repos_update.py, src/funfuzz/util/s3cache.py, src/funfuzz/util/sm_compile_helpers.py, tests/js/test_build_options.py, tests/js/test_shell_flags.py
This enables us to run pylint on Python 3.7 in Travis.
=> Support pylint 2.2.2

.travis.yml, src/funfuzz/js/.eslintrc.js, src/funfuzz/js/jsfunfuzz/avoid-known-bugs.js, src/funfuzz/js/jsfunfuzz/built-in-constructors.js, src/funfuzz/js/jsfunfuzz/detect-engine.js, src/funfuzz/js/jsfunfuzz/driver.js, src/funfuzz/js/jsfunfuzz/error-reporting.js, src/funfuzz/js/jsfunfuzz/gen-asm.js, src/funfuzz/js/jsfunfuzz/gen-grammar.js, src/funfuzz/js/jsfunfuzz/gen-math.js, src/funfuzz/js/jsfunfuzz/gen-proxy.js, src/funfuzz/js/jsfunfuzz/gen-recursion.js, src/funfuzz/js/jsfunfuzz/gen-regex.js, src/funfuzz/js/jsfunfuzz/gen-stomp-on-registers.js, src/funfuzz/js/jsfunfuzz/gen-type-aware-code.js, src/funfuzz/js/jsfunfuzz/mess-grammar.js, src/funfuzz/js/jsfunfuzz/mess-tokens.js, src/funfuzz/js/jsfunfuzz/preamble.js, src/funfuzz/js/jsfunfuzz/run-in-sandbox.js, src/funfuzz/js/jsfunfuzz/run.js, src/funfuzz/js/jsfunfuzz/tail.js, src/funfuzz/js/jsfunfuzz/test-asm.js, src/funfuzz/js/jsfunfuzz/test-consistency.js, src/funfuzz/js/jsfunfuzz/test-math.js, src/funfuzz/js/jsfunfuzz/test-misc.js, src/funfuzz/js/jsfunfuzz/test-regex.js, src/funfuzz/js/package.json, src/funfuzz/js/shared/mersenne-twister.js, src/funfuzz/js/shared/random.js, src/funfuzz/js/shared/testing-functions.js
This PR hooks eslint to test the `src/funfuzz/js` directory on Travis.
Let's do this before making large changes to jsfunfuzz. My plan is to land this, fork off a 0.6.x branch, then go about doing the other old code removals, new feature support and making the shift to template literals after releasing 0.6.x.
Also, [let is the new var](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let). We should move entirely to `let`, right?
(moving to npm module style similar to `octo` might also be on the radar in the future, but taking small steps to get there)
=> Add eslint to jsfunfuzz on Travis

src/funfuzz/autobisectjs/known_broken_earliest_working.py, src/funfuzz/js/compile_shell.py, src/funfuzz/js/inspect_shell.py, src/funfuzz/js/jsfunfuzz/built-in-constructors.js, src/funfuzz/js/jsfunfuzz/detect-engine.js, src/funfuzz/js/jsfunfuzz/driver.js, src/funfuzz/js/jsfunfuzz/error-reporting.js, src/funfuzz/js/jsfunfuzz/gen-asm.js, src/funfuzz/js/jsfunfuzz/gen-grammar.js, src/funfuzz/js/jsfunfuzz/gen-math.js, src/funfuzz/js/jsfunfuzz/gen-proxy.js, src/funfuzz/js/jsfunfuzz/gen-recursion.js, src/funfuzz/js/jsfunfuzz/gen-regex.js, src/funfuzz/js/jsfunfuzz/gen-stomp-on-registers.js, src/funfuzz/js/jsfunfuzz/gen-type-aware-code.js, src/funfuzz/js/jsfunfuzz/mess-grammar.js, src/funfuzz/js/jsfunfuzz/mess-tokens.js, src/funfuzz/js/jsfunfuzz/run-in-sandbox.js, src/funfuzz/js/jsfunfuzz/run.js, src/funfuzz/js/jsfunfuzz/test-asm.js, src/funfuzz/js/jsfunfuzz/test-consistency.js, src/funfuzz/js/jsfunfuzz/test-math.js, src/funfuzz/js/jsfunfuzz/test-misc.js, src/funfuzz/js/jsfunfuzz/test-regex.js, src/funfuzz/js/shared/random.js, src/funfuzz/js/shared/testing-functions.js, src/funfuzz/js/shell_flags.py, src/funfuzz/util/sm_compile_helpers.py, tests/util/test_sm_compile_helpers.py
Here's the first iteration of moving jsfunfuzz entirely to template literals.
In the harness, I have had to bump the earliest known working revision with stable template literal support to [mozilla-central rev bb868860dfc3](https://hg.mozilla.org/mozilla-central/rev/bb868860dfc3).
It should still be possible (manually, on a separate branch), to still bisect back to [current earliest working rev bcacb5692ad9](https://hg.mozilla.org/mozilla-central/rev/bcacb5692ad9) when the testcase is minimized and does not have any template literals left. However, we tend not to need to bisect back that far (in the timeframe of 2015-2017) for most testcases anymore.
I did most of the conversions using WebStorm's "template literal" suggested replacements via Alt-Enter shortcut, plus `eslint` runs during …
=> Move jsfunfuzz to template literals
